version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seu_banco_de_dados
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  springboot-app:
    image: eduardogdfrt/sse.oficina.login:latest
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/seu_banco_de_dados
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
